FROM crelease.devops.vnpt.vn:10000/node:18.16.0-alpine as build
WORKDIR /tmp
COPY package.json package-lock.json .npmrc /tmp/
RUN npm install
COPY . /tmp/
RUN npm run build-staging

FROM crelease.devops.vnpt.vn:10000/nginx:alpine
COPY --from=build /tmp/dist/ang-15-base /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
